### ISSUE TITLE
[BUG] Open intervals with null values don't work: "Could not parse EDTF value '1937/' for indexing node/nid"

### ISSUE THREAD

**Issue by rosiel** [seth-shaw-unlv/controlled_access_terms#109]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When indexing items with an open interval with a null value e.g. '1937/'

* Which page does it occur on?
Errors are in watchdog and come from indexing in EDTF Year.

* What happens?
The years don't get added for faceting. 

* To whom does it occur (anonymous visitor, editor, administrator)?
Content editors / searchers

* What did you expect to happen?
The null-valued intervals should be treated the same as open-ended intervals that use, e.g. `/..`.

**Which version of Islandora are you using?**
2

**Any related open or closed issues to this bug report?**
no

**Screenshots:**
<img width="903" alt="Screenshot 2023-11-02 at 11 55 21 AM" src="https://github.com/Islandora/controlled_access_terms/assets/1943338/0c7afe60-5b48-49e5-aa7c-f8f5dc70d749">

**Comment by seth-shaw-asu** [comment]
Resolved with https://github.com/Islandora/controlled_access_terms/commit/e7990931277f447de752413158d8692ea7f5b17b
