### ISSUE TITLE
[BUG] Year zero does not exist

### ISSUE THREAD

**Issue by AronNovak** [seth-shaw-unlv/controlled_access_terms#125]
**What steps does it take to reproduce the issue?**

Supply `0000` to an EDTF field. There should be a validation error according to https://en.wikipedia.org/wiki/Year_zero . The value is accepted, but nothing is rendered at the node display in the date field.

* When does this issue occur?

* Which page does it occur on?
Node edit / view

* What happens?
Lack of rendered variation, lack of validation error.

* What did you expect to happen?
A validation error should happen, 0000 is not a valid year.

**Comment by seth-shaw-asu** [comment]
EDTF is an extension of ISO 8601 which, according to the Wikipedia article you referenced, _does_ have a year 0. Or, as encoded in EDTF, a year 0000. Ergo, `0000` _is_ valid.

The practical implication the article is that _if_ we were to render it using BC/AD the EDTF value `0000` would be rendered "1 BC".
