### ISSUE TITLE
Push to drupal.org not working

### ISSUE THREAD

**Issue by joshdentremont** [seth-shaw-unlv/controlled_access_terms#135]
Looks like the github action is supposed to push releases to drupal.org, but it is not working. The action looks like it succeeds, but if you look into the details at https://github.com/Islandora/controlled_access_terms/actions/runs/11075091383 you see this line
```
fatal: unable to access 'https://git.drupalcode.org/project/controlled_access_terms.git/': The requested URL returned error: 403
```

This means version 2.4.4 is not available through drupal.org (https://www.drupal.org/project/controlled_access_terms)

**Comment by seth-shaw-asu** [comment]
@joecorall , I heard you fixed the other publish to drupal.org repos. Can you do this one too?

**Comment by joecorall** [comment]
@seth-shaw-asu - i do not have access to edit secrets on this repo. I'll need that to fix it.

**Comment by seth-shaw-asu** [comment]
@joecorall , you are now an admin.

**Comment by joecorall** [comment]
![qhw6n7qigvh41](https://github.com/user-attachments/assets/3d648081-81b5-456e-8737-3106ede8b41a)

I updated `GITLAB_PASSWORD` with my access token generated at https://git.drupalcode.org/-/user_settings/personal_access_tokens. The sync is working now and I published the new release on d.o https://www.drupal.org/project/controlled_access_terms
